@echo off
sqlcmd -Q "RESTORE DATABASE master FROM DISK = '%WORKSPACE%\Schema\%COMPUTERNAME%\master.bck' WITH REPLACE"
sqlcmd -Q "RESTORE DATABASE distribution FROM DISK = '%WORKSPACE%\Schema\%COMPUTERNAME%\distribution.bck' WITH REPLACE"
sqlcmd -Q "RESTORE DATABASE msdb FROM DISK = '%WORKSPACE%\Schema\%COMPUTERNAME%\msdb.bck' WITH REPLACE"
sqlcmd -Q "RESTORE DATABASE ADA FROM DISK = '%WORKSPACE%\Schema\%COMPUTERNAME%\ADA.bck' WITH REPLACE"
